### ISSUE TITLE
mod configuration?

### ISSUE THREAD

**Issue by Dolphos** [Darkorg69/Better-Leveling#10]
So, I am the modpack developer for me and my group of friends and was wondering, if there'd be any possible way to cofigure your mod. eg.: lower the buffs that it gives the player etc..
Thanks in advance! :)

**Comment by Darkorg69** [comment]
Go to: `your_world_folder/serverconfig/`.
There you will find 3 files, 
`betterleveling-gameplay.toml`
`betterleveling-skills.toml`
`betterleveling-specializations.toml`

Everything can be configred.
