### ISSUE TITLE
specialization turns the screen black.

### ISSUE THREAD

**Issue by Gamekolu** [Darkorg69/Better-Leveling#14]
when i choose my first specialization,screen just turns black.i dont know what is wrong but i dont have any other mod or resource pack in use.it could be because of tlauncher but i dont think its the problem because its still working fine if i dont chose my specialization.

**Comment by Darkorg69** [comment]
Please attach all the needed data, like java and mod version, screenshots or video of the bug for additional clarity if applicable.
