### ISSUE TITLE
Duplication / Infinite Ores Bug With Prospecting When Using Silk Touch

### ISSUE THREAD

**Issue by CarbsCode** [Darkorg69/Better-Leveling#2]
In the current build for 1.18.2 (0.3.1) users that have the prospecting skill will see items drop as well as blocks when using silk touch.

Mostly an issue when it comes to mining ores as this drops the items but ALSO because its silk touch it drops the block as well.

This leads to infinite recourses and hopefully can be fixed to not trigger when using tools with silk touch on them!

:)

**Comment by Darkorg69** [comment]
I'm aware of the problem, this problem with many more will be fixed in the upcoming update.

**Comment by CarbsCode** [comment]
Awesome! 😀 Thank you for your hard work!
