### ISSUE TITLE
[1.18.2] [Client] Better Leveling start up crash.

### ISSUE THREAD

**Issue by Cixon** [Darkorg69/Better-Leveling#4]
I can't tell if this is just a general mixin-error or a mod compatibility with NostalgicTweaks. Please take some time to review the files below, thank you!

### log:
[latest.log](https://github.com/Darkorg69/Better-Leveling/files/10678938/latest.log)

### suggestive BetterLeveling crash-log:
[crash-2023-02-07_13.57.21-fml.txt](https://github.com/Darkorg69/Better-Leveling/files/10678967/crash-2023-02-07_13.57.21-fml.txt)

**p.s :** your mod is titled 1.16.5 despite being advertised for 1.18. This is the version in question.[ link.](https://www.curseforge.com/minecraft/mc-mods/better-leveling/files/4376261)

**Comment by Darkorg69** [comment]
The mod you are using is for version 1.16.5, not 1.18.2. 
I just saw that I had marked it as 1.18 version in Curseforge.
It is already fixed. Please use latest 1.18.2 [here](https://www.curseforge.com/minecraft/mc-mods/better-leveling/files/4374646).
