### ISSUE TITLE
Crashing issue

### ISSUE THREAD

**Issue by nix122** [Darkorg69/Better-Leveling#6]
hi sorry to bother you but I seem to be running into an issue when I add your mod to the mod folder for Minecraft it crashes ( I am using forge and the same game version that it is meant for). I do have other mods installed  but as far as I can tell its not a compatibility issue unless it doesn't play nice with other UI mods

**Comment by nix122** [comment]
I forgot to add its 1.19.3

**Comment by Darkorg69** [comment]
Hello, please know that without providing any game logs I cannot help you.

**Comment by nix122** [comment]
I don't know what I did differently but I got it to work
