### ISSUE TITLE
critical hit skill doesn't increase any damage, just critical particle

### ISSUE THREAD

**Issue by ColaLiao** [Darkorg69/Better-Leveling#7]
critical hit skill doesn't increase any damage, just critical particle

 - Game Version: 1.18.2
 - Forge Version: 40.2.0
 - Mod Version: betterleveling-1.18.2-0.5.0

test with TslatEntityStatus (TES) mod

**Comment by Darkorg69** [comment]
Thank you for submitting this issue.

I was able to reproduce the issue and bugfix will be released soon.

**Comment by Darkorg69** [comment]
Issue fixed in 0.6.1
