### ISSUE TITLE
Skill resetted after death even when "Reset on Death" disabled.

### ISSUE THREAD

**Issue by ghost** [Darkorg69/Better-Leveling#8]
When got killed or death by any means then respawn, the skill were gone (include specialities) and must unlock first speciality again even with "Reset on Death" disabled. The skills should be keep even after death.

 - Game Version: 1.18.2
 - Forge Version: 40.2.0
 - Mod Version: betterleveling-1.18.2-0.6.1

**Comment by Darkorg69** [comment]
Hey thank you for submitting your issue. I'm gonna try to reproduce it today. 
Just to note, some unexpected behaviour can occur if your config file is broken. 
Can you try deleting your configs to see if this fixes your problem? 
Configs are located in your world save folder inside the serverconfig folder.

Edit: Confirmed, old entity caps are not revived, will update later today.

**Comment by Darkorg69** [comment]
Fixed in 0.6.2
