### ISSUE TITLE
Strength Skill doesnt work on server

### ISSUE THREAD

**Issue by KevTG** [Darkorg69/Better-Leveling#9]
- Game Version: 1.18.2
 - Forge Version: 40.2.4
 - Mod Version: 0.6.2

the strength skill doesnt work on my server, i have tried to max it out, but there is no difference in my damage, but it seems like some of the other skills work (havent tested all) i have also tested it on singleplayer and it works there. i really think this is a great mod and i dont want to remove it from my server:(

**Comment by Darkorg69** [comment]
Just tested it with default settings and I can't reproduce the bug.
